# This workflow will build a Java project with Maven and scan using CloudDefense github action
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java Maven SCA Scan Action

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  repository_dispatch:

jobs:
  sca-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn clean install
      - name: Cloud Defense Scan
        env:
          SCA_SCAN_URL: https://cd-scanner.herokuapp.com/processAndSave
        uses: cdefense/actions/java@master
        with:
          project-name: vulnerable-java-action
          api-key: ${{ secrets.CD_API_KEY }}
          path: .
